# -*- coding: utf-8 -*-

import random
import tweepy
import time
import sys

CONSUMER_KEY = ''
CONSUMER_SECRET = ''
ACCESS_KEY = ''
ACCESS_SECRET = ''

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_KEY, ACCESS_SECRET)
api = tweepy.API(auth)

def koliikkigeneraattori():
	adj = random.choice(adjektiivit)
	verb = random.choice(verbit)
	subj = random.choice(subjektit)
	obj = random.choice(objektit)
	lopk = random.choice(loppukaneetit)
	lause = adj + " " + subj + " " + verb + " " + obj + "! " + lopk
	aivopieru = lause.upper()
	api.update_status(aivopieru)

adjektiivit = [
  "Likainen",
  "Laiska",
  "Epärehellinen",
  "Poliittisesti korrekti",
  "Masturboiva",
  "Suvaitsevainen",
  "Runkkaava",
  "Ahne",
  "Vasemmistolainen",
  "Perseilevä",
  "Ulkomaalainen",
  "Viisumiton",
  "Kuriton",
  "Perverssi",
  "Paperiton",
  "Kulttuurimarxistinen",
  "sekopäinen",
  "äärivasemmistolainen",
  "epärehellinen"
]

verbit = [
  "raiskaa",
  "loisii",
  "varastaa",
  "tappaa",
  "raiskasi",
  "kähveltää",
  "kähvelsi",
  "koplasi",
  "varasti",
  "tuhopoltti",
  "tuhopolttaa",
  "pihistää",
  "pihisti",
  "kähmi",
  "kähmii",
  "ahmi",
  "kuppaa",
  "rosvoaa",
  "rosvosi",
  "suhmuroi",
  "vatuloi"
]

subjektit = [
  "Sosiaalidemokraatti",
  "Kokoomuslainen",
  "Keskustalainen",
  "Vihreä",
  "Vassari",
  "Kristillisdemokraatti",
  "Eduskunta",
  "Kansanedustaja",
  "EU",
  "USA",
  "Amerikka",
  "Venäjä",
  "Valtamedia",
  "finanssijuutalainen",
  "juutalainen",
  "Muslimi",
  "Punavihreä mädättäjä",
  "Imaami",
  "Turvapaikanhakija",
  "Matu",
  "Maahantunkeutuja",
  "Maahanmuuttaja",
  "Maaham muuttaja",
  "Maahanmuuttajajengi",
  "Turvapaikkaturisti",
  "Pakolainen",
  "Musu",
  "Somali",
  "Afrikkalainen",
  "Terroristi",
  "Laiton maahanmuuttaja",
  "Punavihreä Mädättäjä",
  "Virkamies",
  "Pedofiili",
  "Byrokraatti",
  "loinen",
  "poliittinen korrektius",
  "poliisi",
  "feministi",
  "matuaalto",
  "suvakkinatsi",
  "TE-keskus",
  "Punainen Risti",
  "viranomaisrikollinen",
  "jihadisti",
  "Itäkeskus",
  "yrittäjä",
  "matu",
  "neekeri",
  "rikollinen",
  "hyväveli",
  "hyysäri",
  "sosiaalitantta",
  "kukkahattu",
  "kukkahattutäti",
  "sosialisti",
  "kommunisti",
  "hovioikeus",
  "partalapsi",
  "ministeri",
  "valtamedian toimittaja",
  "huumekauppias",
  "puheenjohtaja",
  "kaupunginjohtaja",
  "valtionvarainministeri",
  "kaupunginvaltuusto",
  "hyysäriämmä",
  "feminatsi",
  "loispummi",
  "ay-pamppu",
  "perverssi",
  "veronkiertäjä",
  "eksoottinen värinä",
  "islamofasisti",
  "kultamuna",
  "pravda",
  "tavjaerkki",
  "väärä mielipide",
  "homosaatio",
  "erilaisuuden liitto",
  "romani",
  "manne",
  "mustalainen",
  "anarkokapitalisti",
  "pizzanpaistaja",
  "kestävä kehitys",
  "reilu kauppa",
  "maanpetturi",
  "liberaalilässy",
  "yritysjohtaja",
  "valtionyhtiö",
  "punavihreä kupla",
  "opiskelija",
  "oikeuslaitos",
  "plutokraatti",
  "pikavippifirma",
  "lesbo",
  "homo",
  "homoseksuaali",
  "transu",
  "vapaamuurari",
  "ehdonalaisvanki",
  "kommari",
  "siviilipalvelusmies",
  "partaimaami",
  "saatananpalvoja",
  "ateisti",
  "kiintiöpakolainen",
  "pakkoruotsittaja",
  "mädättäjä",
  "punavihermädätteinen homopropagandisti",
  "entinen stalinisti",
  "kulttuurinrikastuttaja",
  "preka-eetu",
  "äbäläwäbälä",
  "päättäjä",
  "akkalauma",
  "ammattilusmu",
  "apulaisvaltakunnansyyttäjä",
  "elämäntapaintiaani",
  "globaalikapitalismi",
  "vierasmaalainen",
  "suvakki",
  "sotarikollinen",
  "virkamiesjohtaja",
  "talousnero",
  "mamujengi",
  "rättipää",
  "elinkeinoelämän keskusliitto",
  "porvari",
  "proletariaatti",
  "pakoloinen",
  "lobbari",
  "naispappi",
  "vallassa oleva eliitti",
  "kansainvälinen pääoma",
  "globalisti",
  "nuoriso",
  "yöntimo",
  "sodomiapopulisti",
  "viherpiiperö",
  "sopulitoimittaja",
  "kasinotalous",
  "kansainvälinen kasinotalous",
  "liittovaltio",
  "EU-liittovaltio",
  "pankkiunioni",
  "kunniakansalainen",
  "anarkistiryhmä",
  "muhamettilainen",
  "päättäjä",
  "tuhokapitalisti",
  "arvoliberaali",
  "arvoliberalismi",
  "natsisuvakki",
  "työväenliike",
  "lapatossu",
  "tohvelisankari",
  "halal-liha",
  "vapaamatkustaja",
  "sharia-laki",
  "vellihousu",
  "aseistariisuja",
  "suvakkiämmä",
  "somalineekeri",
  "arvojohtaja",
  "karvalapsi",
  "karvavauveli",
  "moraalisäteilijä",
  "eläkepommi",
  "afromusuarabi",
  "iphone-mies",
  "eurabia",
  "kilpailukykyloikka",
  "punaporvari",
  "vasemmistoradikaali",
  "siirtolainen",
  "suvaitsevaisto"
]

objektit = [
  "rehellisen yrittäjän leivän",
  "keskiluokan ostovoiman",
  "ahkerien suomalaisten verorahat",
  "viattoman perheen lapset",
  "veronmaksajien rahat",
  "kaupungin omaisuutta",
  "lapsiperheiden sosiaalituet",
  "lapsilta leivän pöydästä",
  "Suomen viennin",
  "Vientiyritysten osakkeet",
  "Vanhusten iltapalan",
  "vanhusten aamupalan",
  "vanhusten lounaan",
  "Suomen ylpeyden",
  "isänmaan omavaraisuuden",
  "isänmaan ylpeyden",
  "perheen lapsilisät",
  "perheen toimeentulotuet",
  "työläisten sunnuntailisät",
  "työläisten lomarahat",
  "työläisten palkat",
  "suoraselkäisten suomalaisten naiset",
  "suomalaisten elintavan",
  "yhteiskunnan sosiaalisen järjestelmän",
  "yhteiskunnan moraaliset katsomukset",
  "suomalaisten kulttuuriset arvot",
  "suomalaiset perinteet",
  "kaiken",
  "hyvinvointiyhteiskunnan",
  "hyvinvointivaltion",
  "suomalaisen sosiaaliturvan",
  "suomen itsenäisyyden",
  "suomalaisen lihaa syövän heteromiehen",
  "yhteiskuntasopimuksen",
  "suomen kansallisomaisuuden"
]

loppukaneetit = [
  "kekkonen olisi jo devalvoinut!",
  "rautaa rajalle!",
  "perkele!",
  "saatanan tunarit!",
  "nyt tekis mieli vetää kännit!",
  "vitun hyysärit!",
  "ulos eurosta!",
  "markka takaisin!",
  "helvetin sosiaalitantat!",
  "tukka pois ja linnaan!",
  "kuolemantuomio takaisin!",
  "rajat kiinni!",
  "mestari on oikeassa!",
  "vittusaatanaperkele!",
  "risusavottaan vain!",
  "tuet pois!",
  "köyhät kyykkyyn!",
  "koti uskonto ja isänmaa!",
  "ken ei työtä tee sen ei syömänkään pidä!",
  "perkeleen neekerit!",
  "vientirauha takaisin!",
  "karjala takaisin!",
  "mitä vittua??!?!?!?!?!",
  "palveluspakko takaisin!",
  "saunan takana on vielä tilaa!",
  "holhous ja mokutus on lopetettava!",
  "vittu mitä paskaa!",
  "kuolema vasemmistolle!",
  "oi aikoja oi tapoja!",
  "joutavanpäiväistä humpuukia!",
  "maanpetturit!",
  "mädätystä ja iljetystä!",
  "suomi tarvitsee rautaista johtajaa!",
  "tapainturmelusta!",
  "propagandaa ja agitaatiota!",
  "rikollisillle pakkosterilisaatio välittömästi!",
  "pakkotöihin siivoojaksi!",
  "tukka pois ja siperiaan!",
  "maassa maan tavalla tai maasta pois!",
  "rajat kiinni!",
  "suomi tarvitsee sotilasvallankaappauksen!",
  "höpöhöpöhuttua!",
  "maailmanpokerissa vedätetään!",
  "eurabia on tulevaisuutta!"
]

koliikkigeneraattori()
